### ISSUE TITLE
LW500 Pin

### ISSUE THREAD

**Issue by samsonrosen** [rooi/homebridge-lightwaverf#44]
Hi!

I just picked up an LW500 which is the original lightwave link (I think).

The configuration asks for a pin but having only created an account today I only have a password. Looking closer at the website it shows the attached.

Shall I use the secondary connection method?

Also, is the pairing step compulsory? Can I run the commands from Mac but using the pairing on my PiZero somehow?

Thanks,

Sam
![82709799-5898-4D76-A0FE-1FEA12B319F9](https://user-images.githubusercontent.com/7211878/99718651-1b3dc180-2aa3-11eb-8c2e-988b58548390.png)

**Comment by rooi** [comment]
Hi @samsonrosen,

Sorry I missed this one. 
From what I understand the pin is used for old accounts and the new ones use a password, so I'd say the seconds should work in you case.
Did you manage to connect or find another way to get it working or perhaps a different plugin to achieve something similar?

Roy

**Comment by samsonrosen** [comment]
> Hi @samsonrosen,
> 
> Sorry I missed this one.
> From what I understand the pin is used for old accounts and the new ones use a password, so I'd say the seconds should work in you case.
> Did you manage to connect or find another way to get it working or perhaps a different plugin to achieve something similar?
> 
> Roy

Hi!

It’s working great with the password. I had to use wire shark to get the ID though in the end. Your plugin made it so cheap for me to control my ceiling lights as the LW500 is very cheap second hand - so thanks for writing it.

The only thing not behaving is the the status of the light in Home when I control it using the switch. If I turn the light switch on physically it doesn’t update in home. But I think that might be by design of one way communication?

**Comment by rooi** [comment]
Great that you got it to work!

You're right, the one-way communication causes things to get out of sync when controlling switches manually. Also, sometimes the rf commands are not received by the devices and things may get out of sync as well, since the lightwaverf system has no way successful response mechanism build in.

These are some reasons I looking into other systems, but I did not find one that I liked (with functional switches, dimming, support for many type of bulbs, build in homekit, and functioning without an internet connection) and justify the cost. For myself right now its rf for all light switches/dimmers and the ventilation system with some hue bulbs at locations were there is no physical switch
