### ISSUE TITLE
v1 - everything is a lightbulb

### ISSUE THREAD

**Issue by fitzx** [rooi/homebridge-lightwaverf#46]
Is there any way with the v1 link we can see sockets as sockets and not lightbulbs?   If I ask Siri to 'turn off all the lights' for example all the sockets get turned off too because they get classified as lightbulbs in HomeKit.

Alternatively if there is a way we can use the v2 type config where we can specify what type of device they are?

**Comment by rooi** [comment]
Hi,

That's strange. It should look up the device type and register it as such in homekit. Is it correctly specified in the lightwave or klikaanklikuit app?

Using the v2 type of config is a workaround though. If you set a specific type in the config it should use that instead of the type it find online.

**Comment by fitzx** [comment]
> That's strange. It should look up the device type and register it as such in homekit. Is it correctly specified in the lightwave or klikaanklikuit app?

Yup - here is what some sockets look like in the LightwaveRF app - 
![image](https://user-images.githubusercontent.com/936210/103099485-90526880-4606-11eb-9801-cf75c02e4d5b.jpeg)

And in HomeKit (via HomeBridge) - 

![image](https://user-images.githubusercontent.com/936210/103099516-a829ec80-4606-11eb-8275-7fddf6b1275d.jpeg)

> Using the v2 type of config is a workaround though. If you set a specific type in the config it should use that instead of the type it find online.

Thanks - I'll try that next time I'm tinkering with it.

**Comment by rooi** [comment]
The log should display what devices and which types are found online. My states something as below. With device type 'O' as outlet. You could check and/or copy paste your log to see what's going on. Also, have you noticed the option in homekit to change device types? Press and hold, then setting lower right corner and underneath the room it should allow you to show it as light, socket or ventilator.

device = 
{
  roomId: 5,
  roomName: 'Badkamer',
  deviceId: 2,
  deviceName: 'Ventilatie-3',
  deviceType: 'O'
}
device = 
{
  roomId: 5,
  roomName: 'Badkamer',
  deviceId: 3,
  deviceName: 'Spots',
  deviceType: 'D'
}

**Comment by fitzx** [comment]
This is all I see under room - no option to change device type:

![image](https://user-images.githubusercontent.com/936210/103100726-e249bd00-460b-11eb-8751-a81da5a02dd2.jpeg)

**Comment by fitzx** [comment]
...and logs - 

device = 
{
  roomId: 2,
  roomName: 'Studio',
  deviceId: 1,
  deviceName: 'Door SocketL',
  deviceType: 'L'
}
device = 
{
  roomId: 2,
  roomName: 'Studio',
  deviceId: 2,
  deviceName: 'Door SocketR',
  deviceType: 'L'
}

**Comment by rooi** [comment]
Thx

The 'L' is translated in lights, so that matches what your seeing

I would recommend copying the device list from the log and paste the socket in the config. Than change the 'L' into 'O' and it should work.
You should be able to leave other devices from the config. The plugin should be able to merge both while choosing te device type you've specified manually
